### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by WOLFI3654** [WOLFI3654/SpigotTNTTracer#1]
Create readme for spigot plugin

**Comment by emilyy1231** [comment]
I'll claim, but anybody else if free to contribute if I don't complete.

**Comment by TheTurkeyDev** [comment]
I can create one for ya if you would like to describe what you are looking for it in.

**Comment by WOLFI3654** [comment]
Just a simple readme :D
Explaining what the does and maby a simple How To Install
And it just traces TNT paths

**Comment by TheTurkeyDev** [comment]
I was a bukkit dev back in the day, but isn't installing a plugin simply just dropping the jar into the plugin folder?

**Comment by WOLFI3654** [comment]
Yeah right :D

**Comment by TheTurkeyDev** [comment]
Whats the link to the download page?

**Comment by WOLFI3654** [comment]
Uhm wait

**Comment by WOLFI3654** [comment]
Just look at the Releases

**Comment by TheTurkeyDev** [comment]
Ok. I just stepped away to eat dinner and I will make it for you when I get back

**Comment by WOLFI3654** [comment]
Great. Have a nice meal. Thx <3

**Comment by CNIAngel** [comment]
@Turkey2349 https://github.com/WOLFI3654/SpigotTNTTracer/releases/download/1.0/TnTRracer.jar for direct link or just https://github.com/WOLFI3654/SpigotTNTTracer/releases/ would be better.

**Comment by TheTurkeyDev** [comment]
Yep, I linked to the second one
